### ISSUE TITLE
字典管理编辑和删除功能不可用

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#11]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

字典管理编辑和删除功能不可用，希望可以正常编辑角色详细信息和删除角色

![image](https://user-images.githubusercontent.com/10692860/40887460-b80a1542-677b-11e8-8c5a-0456195c5326.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
done
