### ISSUE TITLE
建议功能性链接改为功能按钮

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#18]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

![image](https://user-images.githubusercontent.com/10692860/40889932-25bff7c6-67a1-11e8-8d10-766fbe410e28.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
按钮与条目操作不一致，也非需要强调的界面，待评估。
