### ISSUE TITLE
CMS页面管理-添加新页面点击保存报500错误

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#21]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

CMS页面管理-添加新页面点击保存报500错误
![image](https://user-images.githubusercontent.com/10692860/40890144-d5b82d68-67a3-11e8-96ea-8477cebd8295.png)

![image](https://user-images.githubusercontent.com/10692860/40890147-e39c1d54-67a3-11e8-83aa-75f54b8440df.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
fixed
