### ISSUE TITLE
CMS文章管理-点击无法新增新文章

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#22]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

CMS文章管理-点击无法新增新文章

![image](https://user-images.githubusercontent.com/10692860/40890154-f4304f0a-67a3-11e8-9197-6a92f5bf4b8e.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
It's working in progress

**Comment by vellengs** [comment]
done
