### ISSUE TITLE
菜单管理修改菜单详情时保存按钮无效

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#23]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

1. 菜单管理修改菜单详情时保存按钮无效
2. 展示文字错误设置管理应改为菜单项管理

![image](https://user-images.githubusercontent.com/10692860/40895235-b7273208-67e0-11e8-9c9b-0131e3ef3aa9.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
fixed
