### ISSUE TITLE
添加角色成员功能不可用

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#25]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

添加角色成员功能不可用，希望可以通过点击用户组，展示出当前用户组下的所有用户，并通过多选的方式进行用户添加。

![image](https://user-images.githubusercontent.com/10692860/40895309-3bee24b0-67e1-11e8-9d40-2b765d640713.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
It's working in progress

**Comment by vellengs** [comment]
done
