### ISSUE TITLE
账号管理 编辑用户组 修改完成后点击SAVE按钮功能无效

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#26]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[X] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

账号管理 编辑用户组 修改完成后点击SAVE按钮功能无效

![image](https://user-images.githubusercontent.com/10692860/40919907-920a35ee-683d-11e8-8acb-563b71576e12.png)

![image](https://user-images.githubusercontent.com/10692860/40920034-fe5ecfac-683d-11e8-8099-6c6ceb8120d7.png)

![image](https://user-images.githubusercontent.com/10692860/40920070-10d91778-683e-11e8-8612-14bdfb48e127.png)

## What is actually happening?

功能待修复

**Comment by vellengs** [comment]
我这边功能正常，能补充下错误信息么？
response 是什么，有没异常？
