### ISSUE TITLE
没有看出项目的优势和作用

### ISSUE THREAD

**Issue by cctv1005s** [vellengs/typerx#28]
>>>
近年来前端技术的野蛮发展，虽然促进了前端岗位的专业化，但逐渐的前后端的割裂也越发明显，这种沟隙不仅在后端产生也包括的系统的设计者。

- typerx 希望帮助前端适当延展到后端, 主要是掌握接口标准化，能模拟后端接口，或者简单实现小型系统后端。

- typerx 希望帮助后端延展到前端，对于非高交互类（无需定制复杂组件，或者基础组件）使用现成的组件、页面复用进行系统生产。

- typerx 希望帮助设计人员，更好的迭代系统设计，保持模型、接口、代码以及文档的同步更新，更好的进行团队交流。

>>>

以下是我提出的几点问题：
1，对第一点的问题：接口的标准化，模拟后端接口是如何实现的？如果是通过这个系统中来写controller实现的话，倒不如用mockjs拦截ajax请求来的方便和快，不需要server的支持。

2，帮助设计人员：哪里能体现帮助设计人员？

希望能回答，谢谢。

**Comment by vellengs** [comment]
1. mockjs 模拟后端始终是孤立的模拟，无法模拟流程的，这很不足，但mockjs 也不是没有用处，你可以在接口初期不写service 层，直接mockjs 返回模拟数据，前端真实的调用很好， 如果原来是纯前端，上手这个项目不难（不需要扩展太多，有很多现成可用的功能，你只要按图着墨即可）， 你可以按目前项目补玩你要的接口即可，无需扩展太多后端深入的知识（当然如果你要完善的系统，后端还是要学习的）。
2. 对于设计人员来说，你可以直接用这个项目完成model 和接口规格的设计，就能生成文档和预览了，可以很好的迭代维护系统所需要的文档。
