### ISSUE TITLE
权限管理筛选功能

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#3]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

初始化状态右边区域应为空，当点击某一行数据时根据选中的条目展示右边功能区

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
done
