### ISSUE TITLE
角色管理模块权限功能

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#4]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

点击权限按钮， 弹出授权页面，进行权限点选择性授权，点击保存后完成授权过程

## References

![image](https://user-images.githubusercontent.com/10692860/40877979-823e1748-66bc-11e8-9003-e166e88abc5a.png)

![image](https://user-images.githubusercontent.com/10692860/40878105-b8e1fce0-66be-11e8-93b6-9dd69b7faa83.png)

**Comment by vellengs** [comment]
done .
