### ISSUE TITLE
菜单管理选中父级后添加时应自动带入参数父级ID

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#5]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

菜单管理选中父级后添加时应自动带入参数父级ID
![image](https://user-images.githubusercontent.com/10692860/40886935-56c5f40c-6773-11e8-844c-4f2874e064fa.png)

![image](https://user-images.githubusercontent.com/10692860/40886959-a66f3fcc-6773-11e8-9233-3ec067564e77.png)

## What is actually happening?

未带入ID，在创建子项时需要再次指定父级
功能待开发

**Comment by vellengs** [comment]
done
