### ISSUE TITLE
添加用户组修改功能

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#6]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

希望能修改用户组详情，如名称等信息
![image](https://user-images.githubusercontent.com/10692860/40887002-4104e88e-6774-11e8-9c64-a1a82589e3ed.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
done
