### ISSUE TITLE
新建账号时自动选中左边区域已选择的用户组

### ISSUE THREAD

**Issue by minliacom** [vellengs/typerx#7]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

1. 新建账号时自动选中左边区域已选择的用户组
2. 在弹出的窗口中帐号名和密码已自动填充了值，待调查是否作用域问题或浏览器自填充功能

![image](https://user-images.githubusercontent.com/10692860/40887035-be3d8432-6774-11e8-8c45-7a48d158ef81.png)

![image](https://user-images.githubusercontent.com/10692860/40887043-fde9999a-6774-11e8-91c2-376e50be16f4.png)

## What is actually happening?

功能待开发

**Comment by vellengs** [comment]
done
